### ISSUE TITLE
Probable conflict with dataview plugin

### ISSUE THREAD

**Issue by PLRrex** [heatherpiper/color-highlighter#2] opened 2024-06-28 08:48 UTC
Not sure if it's only affecting me, but enabling this plugin and the [*Dataview*](https://github.com/blacksmithgu/obsidian-dataview) plugin together seems to cause the following to happen: *dataview inline queries now show up as block elements in reading mode* (that is, no longer being inline).

A minimal example would be to have the following 2 files in your vault, then try viewing the `view_this_in_reading_mode.md` in reading mode.

`source.md`

```markdown
---
title: some text
---

some body text
```

`view_this_in_reading_mode.md`

```markdown
Inline dataview result (should be on the same line but doesn't): `=[[source]].title`
```

I apologize in advance if it turns out to be my own misunderstanding.

**Comment by heatherpiper** [comment] 2024-06-28 22:46
I will have to do some investigating into this. I don't use Dataview myself but I know it's a very popular plugin, so I do want to avoid any conflicts with it. Thanks!

**Comment by heatherpiper** [comment] 2024-07-02 15:30
Came up with a fix for this! Dataview inline queries should now appear as expected in the next release.

The plugin now specifically identifies Dataview inline query results and modifies their HTML structure, converting block-level elements to inline elements and removing line breaks. This ensures that inline query results appear on the same line as intended.

**Closed as completed by heatherpiper** 2024-07-02 15:30 UTC
Labels: bug
